function [ manager ] = get_task_manager(varargin)
    manager = TaskManager();

    manager.add_new_task() ...
        .set_task_path('../external_data/data/pre_pilot/wear_20160907_213514') ... 
        .set_contributor('BH') ...
        .set_wearing_wrist('L') ...
        .set_gnd_time_secs([]) ...
        .set_gnd_events(   {}) ...
        .commit_task();
    
    manager.add_new_task() ...
        .set_task_path('../external_data/data/pre_pilot/wear_20160907_215346') ... 
        .set_contributor('BH') ...
        .set_wearing_wrist('L') ...
        .set_gnd_time_secs([]) ...
        .set_gnd_events(   {}) ...
        .commit_task();
    
    manager.add_new_task() ...
        .set_task_path('../external_data/data/pre_pilot/wear_20160908_174943') ... 
        .set_contributor('BH') ...
        .set_wearing_wrist('L') ...
        .set_gnd_time_secs([]) ...
        .set_gnd_events(   {}) ...
        .commit_task();
    
    manager.add_new_task() ...
        .set_task_path('../external_data/data/pre_pilot/wear_20160908_175207') ... 
        .set_contributor('BH') ...
        .set_wearing_wrist('L') ...
        .set_gnd_time_secs([]) ...
        .set_gnd_events(   {}) ...
        .commit_task();
    
    manager.add_new_task() ...
        .set_task_path('../external_data/data/pre_pilot/wear_20160908_184454') ... 
        .set_contributor('BH') ...
        .set_wearing_wrist('L') ...
        .set_gnd_time_secs([]) ...
        .set_gnd_events(   {}) ...
        .commit_task();
    
    manager.add_new_task() ...
        .set_task_path('../external_data/data/pre_pilot/wear_20160908_185209') ... 
        .set_contributor('BH') ...
        .set_wearing_wrist('L') ...
        .set_gnd_time_secs([]) ...
        .set_gnd_events(   {}) ...
        .commit_task();
    
    % U U L L R R D D <turn my body 90 deg right> U U L L R R D D
    manager.add_new_task() ...
        .set_task_path('../external_data/data/pre_pilot/wear_20160909_121108') ... 
        .set_contributor('BH') ...
        .set_wearing_wrist('L') ...
        .set_gnd_time_secs([3.0, 5.1, 7.5, 9.5, 12.0, 14.5, 17,  19.7, 30.5, 33,  34.8, 36.8, 39,  41.8, 44.5, 46.5]) ...
        .set_gnd_events(   {'U', 'U', 'L', 'L', 'R',  'R',  'D', 'D',  'U',  'U', 'L',  'L',  'R', 'R',  'D',  'D'}) ...
        .commit_task();

end    